name: Docker Build & Publish

on:
  push:
    tags:
      - 'v*.*.*' # Ex: v1.0.0

jobs:
  build-publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/marsrover:latest .
          docker tag ghcr.io/${{ github.repository_owner }}/marsrover:latest ghcr.io/${{ github.repository_owner }}/marsrover:${GITHUB_REF_NAME}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/marsrover:latest
          docker push ghcr.io/${{ github.repository_owner }}/marsrover:${GITHUB_REF_NAME}
